[[Task]]

  # identifier of the include
  include_id = "test"

  # Task name
  name = "test"

  # Command to execute. The first element is the command, the following its arguments.
  # If the command element contains no path seperators, its path is looked up via the $PATH environment variable.
   command = ["./build.sh", "test"]

  # Input or Output includes that the task inherits.
  # Includes are specified in the format <filepath>#<ID>.
  # Paths are relative to the include file location.
  includes = ["{{ .Root }}/baur-includes/inputs.toml#input_buildscript"]

  # Specification of task inputs like source files, Makefiles, etc
  [Task.Input]
    [[Task.Input.GolangSources]]

      # Go package queries, the source files of matching packages and
      # their imported packages are resolved to files.
      # Format:
      # 	file=<RELATIVE-PATH>
      # 	fileglob=<GLOB-PATTERN>	 -> Supports double-star
      # 	Everything else is passed to the Go query tool (go list by default).
      # 	See also the patterns described at:
      # 	<https://github.com/golang/tools/blob/bc8aaaa29e0665201b38fa5cb5d47826788fa249/go/packages/doc.go#L17>.
      # Files from Golang's stdlib are ignored.
      queries = ["./..."]

      # Environment when running the go query tool.
      environment = []

      # List of command-line flags to be passed through to the Go query tool.
      build_flags = []

      # If true queries are resolved to test files, otherwise testfiles are ignored.
      tests = true

[[Task]]

  # identifier of the include
  include_id = "check"

  # Task name
  name = "check"

  # Command to execute. The first element is the command, the following its arguments.
  # If the command element contains no path seperators, its path is looked up via the $PATH environment variable.
   command = ["./build.sh", "check"]

  # Input or Output includes that the task inherits.
  # Includes are specified in the format <filepath>#<ID>.
  # Paths are relative to the include file location.
  includes = ["{{ .Root }}/baur-includes/inputs.toml#input_buildscript"]

  # Specification of task inputs like source files, Makefiles, etc
  [Task.Input]
    [[Task.Input.GolangSources]]

      # Go package queries, the source files of matching packages and
      # their imported packages are resolved to files.
      # Format:
      # 	file=<RELATIVE-PATH>
      # 	fileglob=<GLOB-PATTERN>	 -> Supports double-star
      # 	Everything else is passed to the Go query tool (go list by default).
      # 	See also the patterns described at:
      # 	<https://github.com/golang/tools/blob/bc8aaaa29e0665201b38fa5cb5d47826788fa249/go/packages/doc.go#L17>.
      # Files from Golang's stdlib are ignored.
      queries = ["./..."]

      # Environment when running the go query tool.
      environment = []

      # List of command-line flags to be passed through to the Go query tool.
      build_flags = []

      # If true queries are resolved to test files, otherwise testfiles are ignored.
      tests = true
