[[Input]]

  # identifier of the include
  include_id = "input_buildscript"

  [[Input.Files]]
    # Glob patterns that match files.
    # All Paths are relative to the application directory.
    # Golang's Glob syntax (https://golang.org/pkg/path/filepath/#Match)
    # and ** is supported to match files recursively.
    paths = ["build.sh"]

    # When optional is true a path pattern that matches 0 files will not cause an error.
    optional = false

    # Only resolve to files that are part of the Git repository.
    git_tracked_only = false
